// <auto-generated />
using System;
using ConfigRutina.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfigRutina.Infrastructure.Migrations
{
    [DbContext(typeof(ConfigRutinaDB))]
    [Migration("20251028210123_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfigRutina.Domain.Entities.CategoriaEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaEjercicio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Movilidad"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Calentamiento"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Fuerza"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Hipertrofia"
                        });
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOL");

                    b.Property<int>("IdCategoriaEjercicio")
                        .HasColumnType("integer");

                    b.Property<int>("IdMusculo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("UrlDemo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaEjercicio");

                    b.HasIndex("IdMusculo");

                    b.ToTable("Ejercicio", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.EjercicioSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Descanso")
                        .HasColumnType("INT");

                    b.Property<Guid>("IdEjercicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("INT");

                    b.Property<float>("PesoObjetivo")
                        .HasColumnType("FLOAT");

                    b.Property<int>("RepeticionesObjetivo")
                        .HasColumnType("INT");

                    b.Property<int>("SeriesObjetivo")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("IdEjercicio");

                    b.HasIndex("IdSesionEntrenamiento");

                    b.ToTable("EjercicioSesion", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("GrupoMuscular", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Piernas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Glúteos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pantorrillas"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bíceps"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Tríceps"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Antebrazos Flexor"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Antebrazos Extensor"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Espalda Dorsal y Escapular"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Espalda Lumbar"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Pecho"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Hombros Deltoides"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Hombros Manguito Rotador"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Abdomen y Core"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Zona lumbar"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Cuello y Trapecio Superior"
                        });
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Musculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGrupoMuscular")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupoMuscular");

                    b.ToTable("Musculo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGrupoMuscular = 1,
                            Nombre = "Cuádriceps recto femoral"
                        },
                        new
                        {
                            Id = 2,
                            IdGrupoMuscular = 1,
                            Nombre = "Cuádriceps vasto lateral"
                        },
                        new
                        {
                            Id = 3,
                            IdGrupoMuscular = 1,
                            Nombre = "Cuádriceps vasto medial"
                        },
                        new
                        {
                            Id = 4,
                            IdGrupoMuscular = 1,
                            Nombre = "Cuádriceps vasto intermedio"
                        },
                        new
                        {
                            Id = 5,
                            IdGrupoMuscular = 1,
                            Nombre = "Isquiotibiales bíceps femoral"
                        },
                        new
                        {
                            Id = 6,
                            IdGrupoMuscular = 1,
                            Nombre = "Isquiotibiales semitendinoso"
                        },
                        new
                        {
                            Id = 7,
                            IdGrupoMuscular = 1,
                            Nombre = "Isquiotibiales semimembranoso"
                        },
                        new
                        {
                            Id = 8,
                            IdGrupoMuscular = 1,
                            Nombre = "Aductores mayor"
                        },
                        new
                        {
                            Id = 9,
                            IdGrupoMuscular = 1,
                            Nombre = "Aductores largo"
                        },
                        new
                        {
                            Id = 10,
                            IdGrupoMuscular = 1,
                            Nombre = "Aductores corto"
                        },
                        new
                        {
                            Id = 11,
                            IdGrupoMuscular = 1,
                            Nombre = "Aductores pectíneo"
                        },
                        new
                        {
                            Id = 12,
                            IdGrupoMuscular = 1,
                            Nombre = "Aductores grácil"
                        },
                        new
                        {
                            Id = 13,
                            IdGrupoMuscular = 1,
                            Nombre = "Abductores"
                        },
                        new
                        {
                            Id = 14,
                            IdGrupoMuscular = 2,
                            Nombre = "Glúteo mayor"
                        },
                        new
                        {
                            Id = 15,
                            IdGrupoMuscular = 2,
                            Nombre = "Glúteo medio"
                        },
                        new
                        {
                            Id = 16,
                            IdGrupoMuscular = 2,
                            Nombre = "Glúteo menor"
                        },
                        new
                        {
                            Id = 17,
                            IdGrupoMuscular = 3,
                            Nombre = "Gastrocnemio (gemelo)"
                        },
                        new
                        {
                            Id = 18,
                            IdGrupoMuscular = 3,
                            Nombre = "Sóleo"
                        },
                        new
                        {
                            Id = 19,
                            IdGrupoMuscular = 3,
                            Nombre = "Tibial posterior"
                        },
                        new
                        {
                            Id = 20,
                            IdGrupoMuscular = 3,
                            Nombre = "Plantar"
                        },
                        new
                        {
                            Id = 21,
                            IdGrupoMuscular = 3,
                            Nombre = "Peroneo largo"
                        },
                        new
                        {
                            Id = 22,
                            IdGrupoMuscular = 3,
                            Nombre = "Peroneo corto"
                        },
                        new
                        {
                            Id = 23,
                            IdGrupoMuscular = 4,
                            Nombre = "Bíceps braquial cabeza larga"
                        },
                        new
                        {
                            Id = 24,
                            IdGrupoMuscular = 4,
                            Nombre = "Bíceps braquial cabeza corta"
                        },
                        new
                        {
                            Id = 25,
                            IdGrupoMuscular = 4,
                            Nombre = "Braquial anterior"
                        },
                        new
                        {
                            Id = 26,
                            IdGrupoMuscular = 4,
                            Nombre = "Braquiorradial"
                        },
                        new
                        {
                            Id = 27,
                            IdGrupoMuscular = 5,
                            Nombre = "Tríceps braquial cabeza larga"
                        },
                        new
                        {
                            Id = 28,
                            IdGrupoMuscular = 5,
                            Nombre = "Tríceps braquial cabeza lateral"
                        },
                        new
                        {
                            Id = 29,
                            IdGrupoMuscular = 5,
                            Nombre = "Tríceps braquial cabeza medial"
                        },
                        new
                        {
                            Id = 30,
                            IdGrupoMuscular = 6,
                            Nombre = "Flexor radial del carpo"
                        },
                        new
                        {
                            Id = 31,
                            IdGrupoMuscular = 6,
                            Nombre = "Flexor cubital del carpo"
                        },
                        new
                        {
                            Id = 32,
                            IdGrupoMuscular = 6,
                            Nombre = "Flexor superficial de los dedos"
                        },
                        new
                        {
                            Id = 33,
                            IdGrupoMuscular = 6,
                            Nombre = "Flexor profundo de los dedos"
                        },
                        new
                        {
                            Id = 34,
                            IdGrupoMuscular = 6,
                            Nombre = "Flexor largo del pulgar"
                        },
                        new
                        {
                            Id = 35,
                            IdGrupoMuscular = 6,
                            Nombre = "Palmar largo"
                        },
                        new
                        {
                            Id = 36,
                            IdGrupoMuscular = 6,
                            Nombre = "Pronador redondo"
                        },
                        new
                        {
                            Id = 37,
                            IdGrupoMuscular = 6,
                            Nombre = "Pronador cuadrado"
                        },
                        new
                        {
                            Id = 38,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor radial largo del carpo"
                        },
                        new
                        {
                            Id = 39,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor radial corto del carpo"
                        },
                        new
                        {
                            Id = 40,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor cubital del carpo"
                        },
                        new
                        {
                            Id = 41,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor común de los dedos"
                        },
                        new
                        {
                            Id = 42,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor del meñique"
                        },
                        new
                        {
                            Id = 43,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor largo del pulgar"
                        },
                        new
                        {
                            Id = 44,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor corto del pulgar"
                        },
                        new
                        {
                            Id = 45,
                            IdGrupoMuscular = 7,
                            Nombre = "Extensor del índice"
                        },
                        new
                        {
                            Id = 46,
                            IdGrupoMuscular = 7,
                            Nombre = "Supinador"
                        },
                        new
                        {
                            Id = 47,
                            IdGrupoMuscular = 8,
                            Nombre = "Dorsal ancho"
                        },
                        new
                        {
                            Id = 48,
                            IdGrupoMuscular = 8,
                            Nombre = "Trapecio superior"
                        },
                        new
                        {
                            Id = 49,
                            IdGrupoMuscular = 8,
                            Nombre = "Trapecio medio"
                        },
                        new
                        {
                            Id = 50,
                            IdGrupoMuscular = 8,
                            Nombre = "Trapecio inferior"
                        },
                        new
                        {
                            Id = 51,
                            IdGrupoMuscular = 8,
                            Nombre = "Romboide mayor"
                        },
                        new
                        {
                            Id = 52,
                            IdGrupoMuscular = 8,
                            Nombre = "Romboide menor"
                        },
                        new
                        {
                            Id = 53,
                            IdGrupoMuscular = 8,
                            Nombre = "Redondo mayor"
                        },
                        new
                        {
                            Id = 54,
                            IdGrupoMuscular = 9,
                            Nombre = "Erectores espinales iliocostal"
                        },
                        new
                        {
                            Id = 55,
                            IdGrupoMuscular = 9,
                            Nombre = "Erectores espinales longísimo"
                        },
                        new
                        {
                            Id = 56,
                            IdGrupoMuscular = 9,
                            Nombre = "Erectores espinales espinoso"
                        },
                        new
                        {
                            Id = 57,
                            IdGrupoMuscular = 9,
                            Nombre = "Multífidos"
                        },
                        new
                        {
                            Id = 58,
                            IdGrupoMuscular = 9,
                            Nombre = "Cuadrado lumbar"
                        },
                        new
                        {
                            Id = 59,
                            IdGrupoMuscular = 10,
                            Nombre = "Pectoral mayor porción clavicular"
                        },
                        new
                        {
                            Id = 60,
                            IdGrupoMuscular = 10,
                            Nombre = "Pectoral mayor esternal"
                        },
                        new
                        {
                            Id = 61,
                            IdGrupoMuscular = 10,
                            Nombre = "Pectoral mayor abdominal"
                        },
                        new
                        {
                            Id = 62,
                            IdGrupoMuscular = 10,
                            Nombre = "Pectoral menor"
                        },
                        new
                        {
                            Id = 63,
                            IdGrupoMuscular = 10,
                            Nombre = "Serrato anterior"
                        },
                        new
                        {
                            Id = 64,
                            IdGrupoMuscular = 10,
                            Nombre = "Subclavio"
                        },
                        new
                        {
                            Id = 65,
                            IdGrupoMuscular = 11,
                            Nombre = "Deltoide anterior"
                        },
                        new
                        {
                            Id = 66,
                            IdGrupoMuscular = 11,
                            Nombre = "Deltoide lateral"
                        },
                        new
                        {
                            Id = 67,
                            IdGrupoMuscular = 11,
                            Nombre = "Deltoide posterior"
                        },
                        new
                        {
                            Id = 68,
                            IdGrupoMuscular = 12,
                            Nombre = "Supraespinoso"
                        },
                        new
                        {
                            Id = 69,
                            IdGrupoMuscular = 12,
                            Nombre = "Infraespinoso"
                        },
                        new
                        {
                            Id = 70,
                            IdGrupoMuscular = 12,
                            Nombre = "Subescapular"
                        },
                        new
                        {
                            Id = 71,
                            IdGrupoMuscular = 12,
                            Nombre = "Redondo menor"
                        },
                        new
                        {
                            Id = 72,
                            IdGrupoMuscular = 13,
                            Nombre = "Recto abdominal"
                        },
                        new
                        {
                            Id = 73,
                            IdGrupoMuscular = 13,
                            Nombre = "Oblicuo externo"
                        },
                        new
                        {
                            Id = 74,
                            IdGrupoMuscular = 13,
                            Nombre = "Oblicuo interno"
                        },
                        new
                        {
                            Id = 75,
                            IdGrupoMuscular = 13,
                            Nombre = "Transverso abdominal"
                        },
                        new
                        {
                            Id = 76,
                            IdGrupoMuscular = 13,
                            Nombre = "Diafragma"
                        },
                        new
                        {
                            Id = 77,
                            IdGrupoMuscular = 14,
                            Nombre = "Erectores espinales"
                        },
                        new
                        {
                            Id = 78,
                            IdGrupoMuscular = 14,
                            Nombre = "Multífidos"
                        },
                        new
                        {
                            Id = 79,
                            IdGrupoMuscular = 14,
                            Nombre = "Cuadrado lumbar"
                        },
                        new
                        {
                            Id = 80,
                            IdGrupoMuscular = 15,
                            Nombre = "Trapecio superior"
                        },
                        new
                        {
                            Id = 81,
                            IdGrupoMuscular = 15,
                            Nombre = "Esternocleidomastoideo"
                        },
                        new
                        {
                            Id = 82,
                            IdGrupoMuscular = 15,
                            Nombre = "Escalenos"
                        },
                        new
                        {
                            Id = 83,
                            IdGrupoMuscular = 15,
                            Nombre = "Esplenio del cuello"
                        });
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.PlanEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPlantilla")
                        .HasColumnType("BOOL");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid>("IdEntrenador")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("PlanEntrenamiento", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPlanEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("IdPlanEntrenamiento");

                    b.ToTable("SesionEntrenamiento", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Ejercicio", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.CategoriaEjercicio", "CategoriaEjercicioEn")
                        .WithMany("EjercicioLista")
                        .HasForeignKey("IdCategoriaEjercicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigRutina.Domain.Entities.Musculo", "MusculoEn")
                        .WithMany("EjercicioLista")
                        .HasForeignKey("IdMusculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaEjercicioEn");

                    b.Navigation("MusculoEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.EjercicioSesion", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.Ejercicio", "EjercicioEn")
                        .WithMany("EjercicioSesionLista")
                        .HasForeignKey("IdEjercicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigRutina.Domain.Entities.SesionEntrenamiento", "SesionEntrenamientoEn")
                        .WithMany("EjercicioSesionLista")
                        .HasForeignKey("IdSesionEntrenamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjercicioEn");

                    b.Navigation("SesionEntrenamientoEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Musculo", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.GrupoMuscular", "GrupoMuscularEn")
                        .WithMany("MusculoLista")
                        .HasForeignKey("IdGrupoMuscular")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscularEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.PlanEntrenamiento", "PlanEntrenamientoEn")
                        .WithMany("SesionEntrenamientoLista")
                        .HasForeignKey("IdPlanEntrenamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanEntrenamientoEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.CategoriaEjercicio", b =>
                {
                    b.Navigation("EjercicioLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Ejercicio", b =>
                {
                    b.Navigation("EjercicioSesionLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Navigation("MusculoLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Musculo", b =>
                {
                    b.Navigation("EjercicioLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.PlanEntrenamiento", b =>
                {
                    b.Navigation("SesionEntrenamientoLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Navigation("EjercicioSesionLista");
                });
#pragma warning restore 612, 618
        }
    }
}
