// <auto-generated />
using System;
using ConfigRutina.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfigRutina.Infrastructure.Migrations
{
    [DbContext(typeof(ConfigRutinaDB))]
    [Migration("20251116211051_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfigRutina.Domain.Entities.CategoriaEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaEjercicio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Movilidad"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Calentamiento"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Fuerza"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Hipertrofia"
                        });
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOL");

                    b.Property<int>("IdCategoriaEjercicio")
                        .HasColumnType("integer");

                    b.Property<int>("IdMusculo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("UrlDemo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaEjercicio");

                    b.HasIndex("IdMusculo");

                    b.ToTable("Ejercicio", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.EjercicioSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Descanso")
                        .HasColumnType("INT");

                    b.Property<Guid>("IdEjercicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSesionEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("INT");

                    b.Property<float>("PesoObjetivo")
                        .HasColumnType("FLOAT");

                    b.Property<int>("RepeticionesObjetivo")
                        .HasColumnType("INT");

                    b.Property<int>("SeriesObjetivo")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("IdEjercicio");

                    b.HasIndex("IdSesionEntrenamiento");

                    b.ToTable("EjercicioSesion", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("GrupoMuscular", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Piernas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Glúteos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pantorrillas"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Pecho"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Espalda"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Hombros"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Brazos"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Antebrazos"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Abdomen y Core"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Lumbar"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Cuello y Trapecio"
                        });
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Musculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGrupoMuscular")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupoMuscular");

                    b.ToTable("Musculo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGrupoMuscular = 1,
                            Nombre = "Cuádriceps"
                        },
                        new
                        {
                            Id = 2,
                            IdGrupoMuscular = 1,
                            Nombre = "Isquiotibiales"
                        },
                        new
                        {
                            Id = 3,
                            IdGrupoMuscular = 1,
                            Nombre = "Aductores"
                        },
                        new
                        {
                            Id = 4,
                            IdGrupoMuscular = 1,
                            Nombre = "Abductores"
                        },
                        new
                        {
                            Id = 5,
                            IdGrupoMuscular = 2,
                            Nombre = "Glúteo mayor"
                        },
                        new
                        {
                            Id = 6,
                            IdGrupoMuscular = 2,
                            Nombre = "Glúteo medio"
                        },
                        new
                        {
                            Id = 7,
                            IdGrupoMuscular = 2,
                            Nombre = "Glúteo menor"
                        },
                        new
                        {
                            Id = 8,
                            IdGrupoMuscular = 3,
                            Nombre = "Gemelos"
                        },
                        new
                        {
                            Id = 9,
                            IdGrupoMuscular = 3,
                            Nombre = "Sóleo"
                        },
                        new
                        {
                            Id = 10,
                            IdGrupoMuscular = 4,
                            Nombre = "Pectoral mayor"
                        },
                        new
                        {
                            Id = 11,
                            IdGrupoMuscular = 4,
                            Nombre = "Pectoral menor"
                        },
                        new
                        {
                            Id = 12,
                            IdGrupoMuscular = 5,
                            Nombre = "Dorsales"
                        },
                        new
                        {
                            Id = 13,
                            IdGrupoMuscular = 5,
                            Nombre = "Trapecio medio/inferior"
                        },
                        new
                        {
                            Id = 14,
                            IdGrupoMuscular = 5,
                            Nombre = "Romboides"
                        },
                        new
                        {
                            Id = 15,
                            IdGrupoMuscular = 6,
                            Nombre = "Deltoide anterior"
                        },
                        new
                        {
                            Id = 16,
                            IdGrupoMuscular = 6,
                            Nombre = "Deltoide medio"
                        },
                        new
                        {
                            Id = 17,
                            IdGrupoMuscular = 6,
                            Nombre = "Deltoide posterior"
                        },
                        new
                        {
                            Id = 18,
                            IdGrupoMuscular = 6,
                            Nombre = "Manguito rotador"
                        },
                        new
                        {
                            Id = 19,
                            IdGrupoMuscular = 7,
                            Nombre = "Bíceps"
                        },
                        new
                        {
                            Id = 20,
                            IdGrupoMuscular = 7,
                            Nombre = "Tríceps"
                        },
                        new
                        {
                            Id = 21,
                            IdGrupoMuscular = 8,
                            Nombre = "Flexores"
                        },
                        new
                        {
                            Id = 22,
                            IdGrupoMuscular = 8,
                            Nombre = "Extensores"
                        },
                        new
                        {
                            Id = 23,
                            IdGrupoMuscular = 9,
                            Nombre = "Abdominales superiores"
                        },
                        new
                        {
                            Id = 24,
                            IdGrupoMuscular = 9,
                            Nombre = "Abdominales inferiores"
                        },
                        new
                        {
                            Id = 25,
                            IdGrupoMuscular = 9,
                            Nombre = "Oblicuos"
                        },
                        new
                        {
                            Id = 26,
                            IdGrupoMuscular = 9,
                            Nombre = "Core profundo"
                        },
                        new
                        {
                            Id = 27,
                            IdGrupoMuscular = 10,
                            Nombre = "Zona lumbar"
                        },
                        new
                        {
                            Id = 28,
                            IdGrupoMuscular = 10,
                            Nombre = "Erectores"
                        },
                        new
                        {
                            Id = 29,
                            IdGrupoMuscular = 11,
                            Nombre = "Trapecio superior"
                        },
                        new
                        {
                            Id = 30,
                            IdGrupoMuscular = 11,
                            Nombre = "Cuello"
                        });
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.PlanEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("BOOL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPlantilla")
                        .HasColumnType("BOOL");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid>("IdEntrenador")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("PlanEntrenamiento", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPlanEntrenamiento")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("IdPlanEntrenamiento");

                    b.ToTable("SesionEntrenamiento", (string)null);
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Ejercicio", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.CategoriaEjercicio", "CategoriaEjercicioEn")
                        .WithMany("EjercicioLista")
                        .HasForeignKey("IdCategoriaEjercicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigRutina.Domain.Entities.Musculo", "MusculoEn")
                        .WithMany("EjercicioLista")
                        .HasForeignKey("IdMusculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaEjercicioEn");

                    b.Navigation("MusculoEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.EjercicioSesion", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.Ejercicio", "EjercicioEn")
                        .WithMany("EjercicioSesionLista")
                        .HasForeignKey("IdEjercicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfigRutina.Domain.Entities.SesionEntrenamiento", "SesionEntrenamientoEn")
                        .WithMany("EjercicioSesionLista")
                        .HasForeignKey("IdSesionEntrenamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjercicioEn");

                    b.Navigation("SesionEntrenamientoEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Musculo", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.GrupoMuscular", "GrupoMuscularEn")
                        .WithMany("MusculoLista")
                        .HasForeignKey("IdGrupoMuscular")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscularEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.HasOne("ConfigRutina.Domain.Entities.PlanEntrenamiento", "PlanEntrenamientoEn")
                        .WithMany("SesionEntrenamientoLista")
                        .HasForeignKey("IdPlanEntrenamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanEntrenamientoEn");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.CategoriaEjercicio", b =>
                {
                    b.Navigation("EjercicioLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Ejercicio", b =>
                {
                    b.Navigation("EjercicioSesionLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Navigation("MusculoLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.Musculo", b =>
                {
                    b.Navigation("EjercicioLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.PlanEntrenamiento", b =>
                {
                    b.Navigation("SesionEntrenamientoLista");
                });

            modelBuilder.Entity("ConfigRutina.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Navigation("EjercicioSesionLista");
                });
#pragma warning restore 612, 618
        }
    }
}
